### ISSUE TITLE
Price per use Calculator

### ISSUE THREAD

**Issue by VemAiensi** [VemAiensi/CalcWattCost#3]
Must have inputs for:
> watt
> price per kwh
> hours

*Try it first in Java*

**Comment by VemAiensi** [comment]
# Flowchart

[Click here](https://github.com/VemAiensi/CalcWattCost/blob/main/src/diagrams/flowchart.svg)

**Comment by Torr-sys** [comment]
# your mom

[CalcWattCode](https://github.com/VemAiensi/CalcWattCost/blob/Patrick's-branch/src/test/CalcWattCost.java)

LGTM

**Comment by VemAiensi** [comment]
Nice All done!
